### PR TITLE
Redesign new pricing page

### PR DESCRIPTION
**Pull request by D-Bao**
This new pricing page has been redesigned from scratch and also includes a FAQ section. The text of the list of features and FAQ questions/answers are taken from [https://simplelogin.io/pricing](https://simplelogin.io/pricing).
Feel free to edit the text.

Also for the formatting I ran the command `poetry run djlint --reformat templates` but it removed the indentation, I don't know if that could be an issue.

### CODE REVIEW

**Comment by acasajus** [comment]
Hey, checking on the linting. If you replace in the header block

```
      document.write('<script src="/static/vendor/paddle.js"><\/script>')
```

for 

```  
document.write('<script src="/static/vendor/paddle.js"></script>'); 
```

linting with djlint will work again

**Comment by acasajus** [comment]
Alternatively we can use
```js
    if (window.Paddle === undefined) {
      console.log("cannot load Paddle from CDN");
      var element = document.createElement('script');
      element.src = '/static/vendor/paddle.js';
      document.body.appendChild(element);
}
```

**Comment by D-Bao** [comment]
Thanks for identifying the linting issue. I tried your alternative (with document.head instead of document.body because it said document.body is not defined) however it created an issue with the script at the bottom of the page:

```js
<script type="text/javascript">
  Paddle.Setup({vendor: {{ PADDLE_VENDOR_ID }}});
```
saying `Paddle is not defined`, even if the previous script was successfully added to the document head, probably because it was added too late in the scripts loading queue.

So instead I simply wrote this (may be a little ugly xD):
```js
document.write('<' + 'script src="/static/vendor/paddle.js"><\/script' + '>');
```
which fixed the djlint issue.

**Comment by acasajus** [comment]
Can you try
```
document.prepend(element)
```
instead of `appendChild` to have the element as the first entry of the body?

**Comment by D-Bao** [comment]
I just tried but it also shows the same error

**Comment by acasajus** [comment]
LGTM Ugly but it works :)

**Review by acasajus — APPROVED** [review]
@nguyenkims Once you approve of the changes we can merge.

**Review by nguyenkims — APPROVED** [review]
LGTM!

**Pull request merged**
