### PR TITLE
Binding the docker containers to localhost

### PR DESCRIPTION
**Pull request by prashantkamdar**
As suggested by the OP, updating the readme to bind to locahost.

Kind request to add the label of **hacktoberfest-accepted** when mering the PR.

### CODE REVIEW

**Comment by A-Nicoladie** [comment]
Maybe it would be good to add the same thing for `sl-db` container in upgrade readme file?  
Currently, port 5432 is still exposed.

```
# Pull the latest version
[...]

# Stop SimpleLogin containers
sudo docker stop sl-email sl-migration sl-app sl-db

# Make sure to remove these containers to avoid conflict
sudo docker rm -f sl-email sl-migration sl-app sl-db

[...]

# Run the database container. Make sure to replace `myuser` and `mypassword`
docker run -d \
    --name sl-db \
    -e POSTGRES_PASSWORD=mypassword \
    -e POSTGRES_USER=myuser \
    -e POSTGRES_DB=simplelogin \
    -p 127.0.0.1:5432:5432 \
    -v $(pwd)/sl/db:/var/lib/postgresql/data \
    --restart always \
    --network="sl-network" \
    postgres:12.1

# Run the database migration
[...]

```

**Comment by prashantkamdar** [comment]
hi @A-Nicoladie 
This was a really good suggestion which I had missed.
Thank you for this! Have incorporated this change in the PR.

**Review by nguyenkims — APPROVED** [review]
LGTM! Thanks for making this PR!

**Comment by nguyenkims** [comment]
The PR has been merged and the label `hacktoberfest-accepted` has been added :)

**Pull request merged**
