### PR TITLE
Add export endpoints

### LINKED ISSUE #374: API documentation import/export
Hey,

I would like to export my stuff on a cron job so I always have a local backup, but I can't find API documentation on the import/export. Could this please be documented on https://github.com/simple-login/app/blob/master/docs/api.md? Thanks!

### PR DESCRIPTION
**Pull request by TheLastProject**
Fixes #374 (mostly, no import)

### CODE REVIEW

**Comment by TheLastProject** [comment]
```
Run black --check .
would reformat /home/runner/work/app/app/tests/api/test_custom_domain.py
Oh no! 💥 💔 💥
1 file would be reformatted, 155 files would be left unchanged.
Error: Process completed with exit code 1.
```

This is slightly annoying, I ran Black locally and it said all was fine and I didn't even touch that file :(

**Comment by doanguyen** [comment]
I encountered this previously, did you run black using your own version or the one locked by poetry?

did you try to run black is through poetry, something like: `poetry run black .`

**Comment by TheLastProject** [comment]
```
$ black --version
black, version 20.8b1
```

```
$ poetry run black --version
black, version 20.8b1
```

```
$ poetry run black .
All done! ✨ 🍰 ✨
156 files left unchanged.
```

**Review by nguyenkims — APPROVED** [review]
LGTM, thanks!

**Comment by nguyenkims** [comment]
The black issue is indeed strange as when I run `black` locally, it indeed formats the `test_custom_domain.py` file and my black version is also `black, version 20.8b1` which is pinned in `poetry.lock` file. I'll merge this PR and check if the build still fails.

**Pull request merged**
