### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by szepeviktor**
Fix title of CI workflow

### CODE REVIEW

**Comment by nguyenkims** [comment]
Thanks for spotting this typo!

**Comment by szepeviktor** [comment]
[off] You may know that your direct commits to master are with a non-configured git client.
Please consider committing with your GitHub email address.

**Comment by szepeviktor** [comment]
All I know is listed here https://github.com/szepeviktor/small-project#readme

**Comment by nguyenkims** [comment]
> Please consider committing with your GitHub email address.

Ah I'm not sure to understand, what's the benefit of committing with a Github email address?

**Comment by szepeviktor** [comment]
> what's the benefit of committing with a Github email address?

You don't get this

kép

and your commits will be manageable, for example when you look at "Blame".

**Comment by nguyenkims** [comment]
Oh thanks, after some trials and errors, it finally works now :)

image

**Pull request merged**
