### PR TITLE
Added documentation for custom docker networks

### PR DESCRIPTION
**Pull request by AzuritBadger**
Added said documentation I mentioned in #446

### CODE REVIEW

**Comment by nguyenkims** [comment]
Hey thanks for making this PR! I've thought about this and I think we can simplify this part by:
 
- replacing `240.0.0.0` by `10.0.0.0` in the README.md file. 
- setting the POSTFIX_SERVER to `10.0.0.1` in the Postfix section as if not set, SimpleLogin uses 240.0.0.1 by default.

This shouldn't affect existing user as they will use https://github.com/simple-login/app/blob/95c8f14ea50240c1b59d008ea0dc911dd94da3cd/docs/upgrade.md#L1-L0 for upgrading existing SimpleLogin instance.

What do you think :)?

**Comment by nguyenkims** [comment]
@AzuritBadger sounds good! Do you want to make this change in this PR :)?

**Comment by fareszr** [comment]
@nguyenkims before you merge this
@AzuritBadger you need to edit this, change it to 10.0.0.1
https://github.com/AzuritBadger/app/blob/master/app/config.py#L101

make it `POSTFIX_SERVER = os.environ.get("POSTFIX_SERVER", "10.0.0.1")`

if you don't, the default option will not work.

**Comment by nguyenkims** [comment]
@fareszr the `POSTFIX_SERVER=10.0.0.1` in this PR is set in the `simplelogin.env` would set the correct value for `POSTFIX_SERVER` I think.

**Comment by fareszr** [comment]
> @fareszr the `POSTFIX_SERVER=10.0.0.1` in this PR is set in the `simplelogin.env` would set the correct value for `POSTFIX_SERVER` I think.

still i think if you are going to change the default subnet to 10.0.0.0/24, the default option should change too

**Comment by nguyenkims** [comment]
@fareszr hey updating the default value to 10.0.0.1 would break existing installations as they are using 240.0.0.0 as network and they don't have `POSTFIX_SERVER` set in their config file.

**Comment by AzuritBadger** [comment]
@fareszr Changing the IP in `config.py` isn't neccessary for it to work. While I was figuring out how to use custom networks, I first changed the `POSTFIX_SERVER` variable in `config.py` too, only to find out later that setting `POSTFIX_SERVER` in `simplelogin.env` does the same thing. Besides, as @nguyenkims mentioned, changing the default option would break existing installations. 

I think the best solution would be to always use the gateway of the given Docker network, though I do not know if this is possible to implement.

**Comment by nguyenkims** [comment]
@AzuritBadger the docker network gateway is **usually** 172.17.0.0 though this isn't guaranteed to be the same on all computers. It's then safer to create our own Docker network.

**Comment by AzuritBadger** [comment]
Sorry, I could have phrased it a little better 😅, I actually meant the network that we create for the containers, i.e. `sl-network`. But as I said, thats just an idea, the way it is now works totaly fine as long as the config file is setup as needed.

**Comment by 0xspade** [comment]
The new network for sl-network is not yet implemented in README.md in the main repo.

**Comment by nguyenkims** [comment]
> The new network for sl-network is not yet implemented in README.md in the main repo.

The sl-network is documented in the README right?

image

**Comment by PureFallen** [comment]
> > The new network for sl-network is not yet implemented in README.md in the main repo.
> 
> The sl-network is documented in the README right?
> 
> image

@0xspade probably refers to the changed `sl-network`, the one that is part of this pull request.
I recently started self-hosting SimpleLogin as well and stumbled into the same issue: `RCVD_ILLEGAL_IP`.

While the official instance changed it's network in #44 , the README not mentions the issue of `240.0.0.0` triggering SpamAssassin. Glad i was able to find this pull request by cheer luck.

**Comment by nguyenkims** [comment]
In the latest commit, I've updated to use the 10.0.0.0 network instead of 240.0.0.0 one. I'll close this PR then.

**Pull request closed without merging**
