### PR TITLE
handle the AttributeError that can also be raised by as_bytes()

### PR DESCRIPTION
**Pull request by nguyenkims**

### CODE REVIEW

**Comment by acasajus** [comment]
We could go for a more generic approach to try to get all possible undelying errors with something like:
```python
def to_bytes(msg: Message):
    """replace Message.as_bytes() method by trying different policies"""
    for generator_policy in [None, policy.SMTP, policy.SMTPUTF8]:
        try:
            return msg.as_bytes(policy=generator_policy)
        except Exception as e:
            LOG.w(
                "Error while doing message.as_bytes() with {} policy with error {}".format(
                    generator_policy or "default", e
                )
            )
    msg_string = msg.as_string()
    try:
        return msg_string.encode()
    except Exception as e:
        LOG.w("Error while doing message.as_string().encode() with error {}".format(e))
    return msg_string.encode(error="replace")
```

**Comment by nguyenkims** [comment]
@acasajus it's usually not recommended to use the exception catch-all :) but maybe in this case we don't really have a choice. Hope we can write our own `as_bytes()` in the future.

**Comment by acasajus** [comment]
I would  certainly prefer not to use the catchall but `msg.as_bytes()` is quite unreliable. In this case I'd go for a `do what you can` approach :)

**Comment by nguyenkims** [comment]
@acasajus catch-all approach used in https://github.com/simple-login/app/pull/918/commits/68ec159d9114e1f6440512f0b5a944ff82cfafb8 )

**Comment by acasajus** [comment]
:+1:

**Review by acasajus — APPROVED** [review]

**Pull request merged**
