### PR TITLE
Dockerfile update for cross-os build compatibility

### PR DESCRIPTION
**Pull request by Metabaron1**
This is a prerequisite update for multiarch build to change the python  image tag used (3.7) from "Shared Tags" to any other "Simple Tags" from the same official repository.
Shared Tags can only be pulled on the arch it is intended to be build and used.
Simple Tags allow foreign image to be pulled on any arch for cross-os build.
Else an error is raised: "no matching manifest for linux/amd64 in the manifest list entries"
 https://github.com/docker-library/python/issues/431

I have choosen alpine because it the smaller (but of course you can use another if you want)
 python:3.7 -> python:3.7-alpine

Other changes are related to the image exchange, as alpine may requires some additional packages to be added manually:
 RUN **apt** update && apt install -y vim telnetv ->
 RUN **apk** update && apk add --no-cache vim **busybox-extras build-base libffi-dev libressl-dev musl-dev postgresql-dev python3-dev gnupg**

 apt -> apk missing/replacements:
 telnet -> busybox-extras
 gcc -> build-base
 ffi.h -> libffi-dev
 openssl/opensslv.h -> libressl-dev musl-dev
 psycopg2-binary -> postgresql-dev python3-dev
 gpg -> gnupg

### CODE REVIEW

**Comment by nguyenkims** [comment]
@Metabaron1 hey just to let you know your PR is not forgotten :) (and thanks for making it!). We are going to release a new version soon and will test out the multi arch builds at this moment.

**Comment by Metabaron1** [comment]
Great, thanks.
I suppose you will add theAkito's script to your CI/CD local build.  
I have seen that someone else is also requesting for arm32v7 build:  once you Dockerfile is updated,  if needed, I also can submit a PR to add files required for dockerhub multiarch build , so anyone can build via dockerhub any arch they needed.

**Comment by nguyenkims** [comment]
@Metabaron1 hey I have tried to build the current image on a Mac M1 (ARM) chip and it seems to work well. Do you think we still need to merge the change here?

**Comment by Metabaron1** [comment]
@nguyenkims 
Hi
So long ago that i hadn't tried to rebuild, but  you are right: the python:3.7 image has been updated and they have added all  ARM images to it, great!!
I guess it's thanks to the growing popularity of ARM brought by Apple and now everyone need ARM images lol
So inded  this PR can be close.
Thanks for notifying

**Pull request closed without merging**
